### ISSUE TITLE
Is it a improvement to update 4 times after 16 steps?

### ISSUE THREAD

**Issue by pluveto** [Hauf3n/DDQN-Atari-PyTorch#1]
The code [here ](https://github.com/jihoonerd/Deep-Reinforcement-Learning-with-Double-Q-learning) updates the Q network every 4 steps (4 frames per step), and meanwhile I found your code, every `steps_rollout =16` steps, 4 updates were made through 'for update in range (4)'. Is this an improvement? Could you enlighten me about the purpose and advantage of this?

**Comment by Hauf3n** [comment]
>  Is this an improvement? Could you enlighten me about the purpose and advantage of this?

I dont think that this is an improvement. I am not sure why I wrote it that way. I quickly looked it up [here](https://storage.googleapis.com/deepmind-data/assets/papers/DeepMindNature14236Paper.pdf) (DQN Nature). The authors update their network every 4 steps, so when in doubt use `steps=4`.

**Comment by pluveto** [comment]
OK, thanks
